### ISSUE TITLE
Game Play result for Supervision Mode

### ISSUE THREAD

**Issue by shekharRavi** [GuessWhatGame/guesswhat#12]
Hi, 
I tried to run code in supervised mode using pre-trained model provided (pre-trained models provided is  in supervised mode, not RL mode, right? ). Flags I used  `-skip_training True -oracle_identifier 156cb3d352b97ba12ffd6cf547281ae2 -qgen_identifier 867d59b933a89f4525b189da9d67f17b -guesser_identifier e2c11b1757337d7969dc223c334756a9 -evaluate_all False -store_games True` . Since code was expecting `params.ckpt` in [loop_saver](https://github.com/GuessWhatGame/guesswhat/blob/master/src/guesswhat/train/train_qgen_reinforce.py#L186) in current session. I simply copy pasted files provided in loop folder session `loop/e3a6b91687fa1589696f5969b1433a47` as provided in pre-trained model. (I could have simply commented that line, it is needed only in case of reinforce mode)
With the above setting setting when I run the code, I get gibberish dialogues for all the games in case of New Game.  Also, it saves `id` starting from `0`. I don't see any game having `id = 0` in the testset.

**Comment by fstrub95** [comment]
Actually,
I am not sure to understand what you are exactly doing:
Do you have folders with:

out/oracle/156cb3d352b97ba12ffd6cf547281a/...
out/qgen/867d59b933a89f4525b189da9d67f17b/...
out/guesser/e2c11b1757337d7969dc223c334756a9/...
and a folder with the downloaded vgg features + dict.json

data/guesswhat.test.tar.gz
data/dict.json
data/guesswhat.test.tar.gz
data/ft_vgg_ing/test_features.h5
config/loop/config.json

Then, you  just have to run:

python src/guesswhat/train/train_qgen_reinforce.py
    -data_dir data/ \
    -exp_dir out/loop/ \
    -config config/looper/config.json \
    -img_dir data/ft_vgg_img \
    -crop_dir data/ft_vgg_crop \
    -networks_dir out/ \
    -oracle_identifier 156cb3d352b97ba12ffd6cf547281a \
    -qgen_identifier 867d59b933a89f4525b189da9d67f1 \
    -guesser_identifier e2c11b1757337d7969dc223c334756 \
    -evaluate_all false \
    -store_games true ´\
    -skip_training \
    -no_thread 2

That will evaluate the supervised model.
Note that if you do not have the good features or the good dict, it is not
going to work.
Use the one I provide on the website to avoid any issue.

In the generated games, I put id = 0. Indeed, one is free to generate new games that does not exist in the dataset.
Yet, If you still want to compare with the testset, you can use the array index (after removing incomplete games if I remember well).

**Comment by fstrub95** [comment]
oh, I see: I just detected that extra-line that should not be here: https://github.com/GuessWhatGame/guesswhat/commit/a004090805387dda38972f8bbdfee25ce353d0a8

This may be the root of your issue

**Comment by shekharRavi** [comment]
Thanks got it working. There was also issue with dict file, I used mine instead of provided one.
