### ISSUE TITLE
COCO API not detected

### ISSUE THREAD

**Issue by mep-cmu** [GuessWhatGame/guesswhat#13]
When I train the exxtract feature as well as train the oracle, I see this:
Coco API was not detected - advanced segmentation features cannot be used. 
How can I resolve this?

Also the latest commit is not able to recursively clone all the dependencies.

**Comment by fstrub95** [comment]
Hi!
Regarding the coco-api, you just need to compile the it. (go to coco-api, look for makefile, make)
Yet, we are not (yet) using it in the master code. Actually, the warning is a bit premature.

regarding the github dependency, did you try:
git clone --recursive https://github.com/GuessWhatGame/guesswhat.git

It works on my side:
git clone --recursive https://github.com/GuessWhatGame/guesswhat.git
Cloning into 'guesswhat'...
remote: Counting objects: 919, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 919 (delta 49), reused 66 (delta 25), pack-reused 820
Receiving objects: 100% (919/919), 193.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (530/530), done.
Checking connectivity... done.
Submodule 'src/cocoapi' (git@github.com:GuessWhatGame/cocoapi.git) registered for path 'src/cocoapi'
Submodule 'src/generic' (https://github.com/GuessWhatGame/generic) registered for path 'src/generic'
Submodule 'src/neural_toolbox' (https://github.com/GuessWhatGame/neural_toolbox) registered for path 'src/neural_toolbox'
Cloning into 'src/cocoapi'...
remote: Counting objects: 944, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 944 (delta 6), reused 13 (delta 4), pack-reused 924
Receiving objects: 100% (944/944), 11.69 MiB | 3.70 MiB/s, done.
Resolving deltas: 100% (558/558), done.
Checking connectivity... done.
Submodule path 'src/cocoapi': checked out '8b2b4e48420bee8500ae2b78187256b3a7bcb025'
Cloning into 'src/generic'...
remote: Counting objects: 303, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 303 (delta 13), reused 20 (delta 8), pack-reused 271
Receiving objects: 100% (303/303), 58.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (188/188), done.
Checking connectivity... done.
Submodule path 'src/generic': checked out '3df6c8fa5861bdd09679a186422ff9b67660df79'
Cloning into 'src/neural_toolbox'...
remote: Counting objects: 61, done.
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 61
Unpacking objects: 100% (61/61), done.
Checking connectivity... done.
Submodule path 'src/neural_toolbox': checked out '268c4ac760f13fa8bacf0d0ee2a0d76db736c96c'

If it still does not work, can you give me more details (missing package etc.)

Florian
