### ISSUE TITLE
Possible bug in spatial features calculation.

### ISSUE THREAD

**Issue by AashishV** [GuessWhatGame/guesswhat#14]
Hi,

Calculation of y_lower in Bbox is incorrect. As you can see from the below figure, the y-axis starts from the upper left corner and not the lower left corner as assumed in the code here, https://github.com/GuessWhatGame/guesswhat/blob/master/src/guesswhat/data_provider/guesswhat_dataset.py#L69. Therefore, it should be **self.y_upper = bbox[1]** and  **self.y_lower = self.y_upper + self.y_height**. 

![screenshot from 2018-01-04 19-43-03](https://user-images.githubusercontent.com/3125480/34579236-69fe34f0-f188-11e7-93ae-613e119d9ee5.png)

Also, I crosschecked it with MS COCO API which also adds the height of the bounding box. This can be seen here,
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py#L327.

And I agree that this is a very small bug and may not vary the performance of the overall system. But might improve scores of Oracle configurations where the image features of the crop is taken into account.

**Comment by fstrub95** [comment]
Hi Aashish, 
In the codebase, we do not follow COCO format to compute the bounding box... but PIL format.
So, it should not be buggy.

cf image_preprocessor.py
    # Create crop with tuple defining by left, upper, right, lower (Beware -> y descending!)
    crop = raw_img.crop(box=(x_left, im_height-y_upper, x_right,im_height-y_lower))

I agree that all those formating provide some terrible headaches.  Yet, the point is to be consistent.
I will add more comments to avoid such confusion.

Florian

**Comment by AashishV** [comment]
Thanks for the clarification.

**Comment by fstrub95** [comment]
Hi Aashish, 
In the codebase, we do not follow COCO format to compute the bounding box... but PIL format.
So, it should not be buggy.

cf image_preprocessor.py
    # Create crop with tuple defining by left, upper, right, lower (Beware -> y descending!)
    crop = raw_img.crop(box=(x_left, im_height-y_upper, x_right,im_height-y_lower))

I agree that all those formating provide some terrible headaches.  Yet, the point is to be consistent.
I will add more comments to avoid such confusion.

Florian
