### ISSUE TITLE
Is there any code that can evaluate performance?

### ISSUE THREAD

**Issue by yellowjs0304** [GuessWhatGame/guesswhat#15]
Hi, I have read your paper. 
It was Cool.
I wish to execute your model. (NOT Training . Just your pretrained model.)
Is there any code that can evaluate performance into GUI like masked(target object) output image or Dialogues(between two player).
I can't find in your GitHub page. 
Thank you.

**Comment by fstrub95** [comment]
Hi Jisu,
There is no GUI to evaluate your model for now.
You can use the following script to have an interactive evaluation of you
model:
https://github.com/GuessWhatGame/guesswhat/blob/master/src/guesswhat/eval/interactive_dialogue.py
And if you want to only compute the accuracy, you use the flag skip_train
in the file trin_qgen_reinforce.py
Tell me if you have additional questions.
Kind regards
Florian

**Comment by yellowjs0304** [comment]
Thank you for reply.

**Comment by fstrub95** [comment]
hmm, i forgot to push the config file...
Done!
https://github.com/GuessWhatGame/guesswhat/tree/master/config/eval
