### ISSUE TITLE
Link to the test images missing and Mod values of files needed

### ISSUE THREAD

**Issue by ash567** [GuessWhatGame/guesswhat#19]
The link to download the test set is missing. Is it same as the MS COCO test, train and val 2014 split?

" 
> To download the MS Coco dataset, please follow the following instruction:
>  
> wget http://msvocds.blob.core.windows.net/coco2014/train2014.zip -P data/img/
> unzip data/img/train2014.zip -d data/img/raw
> 
> wget http://msvocds.blob.core.windows.net/coco2014/val2014.zip -P data/img/
> unzip data/img/val2014.zip -d data/img/raw
> 
"

Also after downloading the files what are the md5sum values with which I can compare my md5sum values?

**Comment by fstrub95** [comment]
Hi Ash, 
We did not use the same split as MsCoco. 
Indeed, we need the ground segmentation/category etc. ground truth to generate games. So, we did not use MsCoco Test and we had to define a new image split.
Kind regards
Florian

**Comment by ash567** [comment]
Thanks for answering.

I have a few more quires. Even if the split up is different, are the images present in the MS COCO 2014 val and train set same as the images present in the val, train and test set of GuessWhat dataset set? So if I download MS COCO train set, will it be equivalent to downloading the file you download using "wget http://msvocds.blob.core.windows.net/coco2014/train2014.zip -P data/img/"?

**Comment by fstrub95** [comment]
Hi Ash, 
You can download the MSCoco train/test and then use the script python rewire_coco_image_id.py.
It will create symlink to all the image into a single file.
When you will create the image features, it will genrate the train/val/test automatically

http://msvocds.blob.core.windows.net/coco2014/train2014.zip is the official MS COCO link :)

Florian

**Comment by ash567** [comment]
Thanks for answering all the queries. I really appreciate it.
