### ISSUE TITLE
Cannot get dataset now (2022/7/12)

### ISSUE THREAD

**Issue by Ryosuke0104** [GuessWhatGame/guesswhat#32]
I can't find dataset which I can download.
This url (https://florian-strub.com/guesswhat.test.jsonl.gz) may be broken.

Please let me know how to get this dataset now.
Thank you.

**Comment by harm-devries** [comment]
Thanks for reporting this. @fstrub95 will check this once he's back from vacation.

**Comment by Ryosuke0104** [comment]
Thank you for replying.
Ok.

**Comment by fstrub95** [comment]
It is back online :)
