### ISSUE TITLE
Oracle Training with Image

### ISSUE THREAD

**Issue by shekharRavi** [GuessWhatGame/guesswhat#5]
Hi, 

 First of all thanks for the releasing the code. 

 I am trying to train Oracle with full image,  
`batchifier = OracleBatchifier(tokenizer, sources, status=config['status'], **config['model']['crop'])`
 getting following error 
`Traceback (most recent call last):
  File "guesswhat/train/train_oracle.py", line 113, in <module>
    batchifier = OracleBatchifier(tokenizer, sources, status=config['status'], **config['model']['image'])
TypeError: __init__() got an unexpected keyword argument 'image_input'`

 Error is resulting due to `**config['model']['image']`. Replacing `**config['model']['image']` with `*config['model']['image']` and provide status as list i.e `batchifier = OracleBatchifier(tokenizer, sources, status=[config['status'], *config['model']['crop']])` results in following error 
`ValueError: zero-size array to reduction operation maximum which has no identity`

Code works with
`batchifier = OracleBatchifier(tokenizer, sources, status=config['status'])` but I am not sure it is correct or not. 

Thanks.

**Comment by fstrub95** [comment]
The new version should be fine, I am retraining the oracle from scratch to be sure.

**Comment by shekharRavi** [comment]
Thanks, Oracle is working now. 
Just to let you know that in the latest merge `src/generic` link is broken.
