### ISSUE TITLE
about reported results

### ISSUE THREAD

**Issue by JasZhanAva** [GuessWhatGame/guesswhat#8]
I'm bit confused about the reported results, both baseline and reinforcement results are different from the paper[2]. Which one should be used for reference, the github one or the paper[2]? I test the pre-trained cross-entropy models and get 0.375, which is close to the github one.

**Comment by fstrub95** [comment]
Hi,
As mentioned on github, you should refer to the results in the github page
(or the one you reproduce).
We noticed a bug after publishing the paper. As fixing the bug improves the
final score (!), we did not withdraw the paper.
Besides, the motivation, RL definition, algorithms still hold!
An updated version of the paper will be pushed on arxiv with
a more in-depth analysis of the results.

**Comment by JasZhanAva** [comment]
Thanks for the clarification! :)
